name: â° Create weekly pull request

on:
  schedule:
    - cron: 0 11 * * 1

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Checkout repository
        uses: actions/checkout@v2

      - name: ğŸ” Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: staging
          base: production
          title: â° Weekly merge from staging into production
          body: |
            This pull request was made by a [weekly workflow][1].

            [1]: https://github.com/MaxAltena/maxaltena.com/actions?query=workflow%3A%22%E2%8F%B0+Create+weekly+pull+request%22
          commit-message: â° Weekly merge from staging into production
